apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-readiness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-readiness
  template:
    metadata:
      labels:
        app: liveness-readiness
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: sygnia
          image: shaypi/sygnia:finals
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /lazy
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - cat
                - hello
            initialDelaySeconds: 15
            periodSeconds: 10
